version: "3"
services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:6.0.8
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data/:cached
    logging:
      driver: none

volumes:
  db-data:
  redis-data:
