apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy/pg-volume.yaml
  - deploy/postgres.yaml
  - deploy/secret.yaml
  - deploy/den.yaml
  - deploy/gecko.yaml
  - deploy/arroyo.yaml