replicaCount: 1

selectorLabels:
  app: website

image:
  repository: website
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000

healthcheck:
  enabled: false
  path: /health

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
