apiVersion: apps/v1
kind: Deployment
metadata:
  name: arroyo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: arroyo
  template:
    metadata:
      labels:
        name: arroyo
    spec:
      containers:
      - name: arroyo
        image: arroyo:latest
        imagePullPolicy: Never
        envFrom:
        - secretRef:
            name: app-secrets
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            path: /health
            port: 3000
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          httpGet:
            path: /health
            port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: arroyo-service
  namespace: default
spec:
  type: NodePort
  selector:
    name: arroyo
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001