apiVersion: apps/v1
kind: Deployment
metadata:
  name: gecko
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gecko
  template:
    metadata:
      labels:
        app: gecko
    spec:
      containers:
      - name: gecko
        image: gecko:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gecko-service
spec:
  type: ClusterIP
  selector:
    app: gecko
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000